# Generated by Django 5.2.1 on 2025-05-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeabonnement',
            name='duree',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
