# Generated by Django 5.2.1 on 2025-05-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_abonnement_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='apiuser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='statut_paiement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
