# Generated by Django 5.2.1 on 2025-05-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_abonnement_apiuser_abonnement_statut_paiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
