# Generated by Django 5.2.1 on 2025-05-27 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_abonnement_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='abonnement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.abonnement'),
        ),
    ]
