# Generated by Django 5.2.1 on 2025-05-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_paiement_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
