# Generated by Django 5.2.1 on 2025-05-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_diagnostic_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendezvous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('immatriculation', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
