# Generated by Django 5.2.1 on 2025-05-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rendezvous'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='phone',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
