# Generated by Django 5.2.1 on 2025-05-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rendezvous_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='motif',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
